config:
    pattern:    /
    defaults:   {_controller: main:check}

install:
    pattern:    /configTiitz/install
    defaults:   {_controller: main:check}


entityGenerator:
    pattern:    /configTiitz/generator
    defaults:   {_controller: generator:generateEntity}