config:
    pattern:    /
    defaults:   {_controller: main:check}

install:
    pattern:    /configTiitz/install
    defaults:   {_controller: main:check}


#entityGeneratorPOST:
#    pattern:    /configTiitz/entityGenerator
#    defaults:   {_controller: generator:posted}
#    requirements:
#    	_method: POST

entityGenerator:
    pattern:    /configTiitz/entityGenerator
    defaults:   {_controller: generator:generateEntity}

