
# Routing
    routing:
    type:		yml

# Template Engine
    template:    twig

# language (tool development)
    language:    fr

# environnement (dev | prod)
    environnement:    dev

# Permit to check if a project is already started
    existingprojet:    true