blog_pute:
    pattern:   /blog/pute
    defaults:  { _controller: AcmeBlogBundle:Blog:show }

blog_show:
    pattern:   /blog/{slug}
    defaults:  { _controller: AcmeBlogBundle:Blog:show }

test_show:
    pattern:	/test/show
    defaults:	{ _controller: test:test:show}