blog_beng:
    pattern:   /blog/beng
    defaults:  { _controller: Blog:beng }
    requirement: { method: NORMAL  }

blog_beng:
    pattern:   /blog
    defaults:  { _controller: Blog:show }
    requirement: { method: NORMAL  }

blog_default:
    pattern:   /
    defaults:  { _controller: Blog:home }

blog_show:
    pattern:   /blog/article/{slug}/comment/{lol}
    defaults:  { _controller: Blog:show }
