configInstall:
    pattern:    /configTiitz/install
    defaults:   {_controller: gui:check}
    
configInstall:
    pattern:    /configTiitz/
    defaults:   {_controller: gui:check}

configInstall:
    pattern:    /
    defaults:   {_controller: gui:check}

checkBDD:
    pattern:    /configTiitz/checkBDD
    defaults:   {_controller: checkBDD:checkBDD}
